# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the local code to the container
COPY . /app

# Install the required dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that the app will run on
EXPOSE 4000

# Set the environment variable to avoid Python buffering logs
ENV PYTHONUNBUFFERED=1

# Command to run the app when the container starts
CMD ["python", "app.py"]
